### ISSUE TITLE
Submit channel jobs

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/CNN#29]
I've just compared the `iss27` branch with `temp`.

```
git diff --minimal iss27 temp scripts/genome_wide|grep "+++"
+++ b/scripts/genome_wide/SGE_scripts/make_channel.sge
+++ b/scripts/genome_wide/SGE_scripts/submit_channel_jobs.sh
+++ b/scripts/genome_wide/clipped_read_pos.py
+++ b/scripts/genome_wide/clipped_reads.py
+++ b/scripts/genome_wide/snv.py
+++ b/scripts/genome_wide/split_reads.py
```
The first two SGE scripts seem redundant to me as we already have the GE/Slurm `run.sh` script, which also supports a list of SeqIDs (e.g. chromosomes; see https://github.com/GooglingTheCancerGenome/CNN/commit/e01f77f23cb72b23d0316461a74b2e90c196dc21). The remaining `*.py` scripts have updated CLI (i.e. support a chromosome list). However, this won't be needed for parallel execution (per chromosome). Perhaps I miss something?

**Comment by lsantuari** [comment]
For the SGE scripts, I agree. I can use `run.sh` and `run_local.sh`.
The scripts `clipped_read_pos.py`, `clipped_reads.py` and `split_reads.py` at the moment cannot be run in parallel per chromosome, because of the need to consider both read and read mate. They are run on the full BAM file, but a chromosome list is still specified, so the results can be restricted to the chromosomes in the list.
The script `snv.py` is run in parallel on each chromosome.

**Comment by lsantuari** [comment]
We need `clipped_read_pos.py`, `clipped_reads.py` and `split_reads.py` (with the chromosome list as parameter) from `temp` for the `iss27` (and the `iss27_fix`) branch. Can we merge those files from `temp` into `iss27`?

**Comment by lsantuari** [comment]
To be added: why `clipped_read_pos.py`, `clipped_reads.py` and `split_reads.py` needs to be run per BAM file and not per chromosome.
